### ISSUE TITLE
Lesson Request: Read and write Files

### ISSUE THREAD

**Issue by quocdat32461997** [pekkalacd/Introduction-to-Python#1]
Read and write files is necessary. Especially, writing .pickle file to save memory.

**Comment by pekkalacd** [comment]
That's a great point. There is a section for reading/writing python files labeled **Working with Files** on the [Table of Contents](https://github.com/pekkalacd/Introduction-to-Python/blob/master/Table%20Of%20Contents.md); but I did not mention .pickle files there. So, that can be added to the description of that section. 

<br>

Would you like to contribute some examples of reading / writing files in Python and/or using .pickle file to save memory? 
You could add it [**here**](https://github.com/pekkalacd/Introduction-to-Python/tree/master/Lessons/Working%20with%20Files).
