### ISSUE TITLE
Add to Packages, Libraries, and Modules

### ISSUE THREAD

**Issue by quocdat32461997** [pekkalacd/Introduction-to-Python#22]

**Comment by quocdat32461997** [comment]
Packages, Libraries, and Modules vs Multiple Python Files
Should be merged? @pekkalacd

**Comment by pekkalacd** [comment]
yeah I think that's fine.

**Comment by quocdat32461997** [comment]
great. Then, I'll merge working w/ files, working w/ multiple files, and packages, libraries, and modules altogether.
