### ISSUE TITLE
Add Structure to the Repository

### ISSUE THREAD

**Issue by pekkalacd** [pekkalacd/Introduction-to-Python#8]
[x] Got rid of the Examples folders in each sub-lesson folder.
[x] Updated README for repository with new structure. 

Here's what's needed: 
[] Need to get rid of the Exercises folders in each sub-lesson folder. 
[] Need to add OVERVIEW.md to each lesson sub folder
[] Need to add EXAMPLES.md to each lesson sub folder
[] Need to add EXERCISES.md to each lesson sub folder
[] Need to re-write the available Basic Overview jupyter notebook  into markdown and save as OVERVIEW.md for the Basic Overview lesson folder. Also need to update the ending note on that file to not forward user to EXAMPLES folder but to instead EXAMPLE.md for set up instructions & installation of Python 3. 

Reason for changes: 
Per recent information, it seems using jupyter notebooks would be complicated in terms of contributing. So, instead OVERVIEW.md will have the overview for each lesson, EXAMPLES.md will have the example code for each lesson, and EXERCISES.md will have the exercises that users can have to practice the information presented in each lesson.

**Comment by pekkalacd** [comment]
I'll transcribe the existing Basic Overview jupyter notebook into a markdown file and store as OVERVIEW.md and edit the last note.

**Comment by quocdat32461997** [comment]
Added:
* Overview
* Examples
* Exercises

**Comment by quocdat32461997** [comment]
Remove Exercises folder

**Comment by quocdat32461997** [comment]
@pekkalacd custom_name.md wont pop up as the main markdown file in each folder that visitors have to find and click to OVERVIEW.md (kinda incovenient). Suggest: rename OVERVIEW.md to README.md.

**Comment by pekkalacd** [comment]
@quocdat32461997 yes - let's rename OVERVIEW.md to README.md. I'll edit the intro README.md to reflect the changes.

**Comment by quocdat32461997** [comment]
> @quocdat32461997 yes - let's rename OVERVIEW.md to README.md. I'll edit the intro README.md to reflect the changes.

Renamed

**Comment by quocdat32461997** [comment]
@pekkalacd if nothing else, please close the issue.
